build_from:
  aarch64: docker.io/library/python:3.13-alpine
  amd64: docker.io/library/python:3.13-alpine
  armhf: docker.io/library/python:3.13-alpine
  armv7: docker.io/library/python:3.13-alpine
  i386: docker.io/library/python:3.13-alpine
